import requests # library used to make HTTP requests to the Hugging Face API
from config import HF_API_KEY
from colorama import Fore, Style, init # Foreground color and style for terminal output, init to initialize colorama settings

# Initialize colorama for colored terminal output
init(autoreset=True) # initialize colorama with autoreset to automatically reset colors after each print statement

# Default model name that can be easily changed
DEFAULT_MODEL = "google/pegasus-xsum" # Pegasus is a powerful summarization model, offers consize outputs for news articles and short form texts.

def build_api_url(model_name):
    return f"https://api-inference.huggingface.co/models/{model_name}"

def query(payload, model_name=DEFAULT_MODEL):
    # parameters: payload (the input data for the model): dictionary containing inputs and parameters for the api. model_name (the specific Hugging Face model to use, default is set to DEFAULT_MODEL)
    """
    Sends a POST request to the Hugging Face API using the specified model.

    """
    api_url = build_api_url(model_name)
    headers = {"Authorization": f"Bearer {HF_API_KEY}"} # sets up http headers for api calls, including the authorization header with the api key
    response = requests.post(api_url, headers=headers, json=payload) # Makes a POST request to the Hugging Face API with the specified URL, headers, and JSON payload containing the input data and parameters for the model.
    return response.json() # returns the response from the API as a JSON object, which can be processed to extract the generated summary or handle any errors that may occur during the API call.

def summarize_text(text, min_length, max_length, model_name=DEFAULT_MODEL):
    # Defines a function to summarize text using the Hugging Face API. It takes the input text, minimum and maximum length for the summary, and an optional model name (defaulting to DEFAULT_MODEL).
    payload = {
        "inputs": text,
        "parameters": {"min_length": min_length, "max_length": max_length}
    }
    print(Fore.BLUE + Style.BRIGHT + f"\n???? Performing AI summarization using model: {model_name}")
    result = query(payload, model_name=model_name)
    # variable 'result' will contain the response from the Hugging Face API, which should include the generated summary based on the input text and specified parameters. The function then checks if the response is in the expected format and extracts the summary text if available, otherwise it prints an error message.

    # Check if the response has the expected format
    if isinstance(result, list) and result and "summary_text" in result[0]: # checks if the result is a list, is not empty, and contains the key "summary_text" in the first element of the list. This is the expected format for a successful response from the Hugging Face summarization API.
        return result[0]["summary_text"]
    else:
        print(Fore.RED + "❌ Error in summarization response:", result)
        return None

if __name__ == "__main__":
    # Ask for the user's name
    print(Fore.YELLOW + Style.BRIGHT + "???? Hi there! What's your name?")
    user_name = input("Your name: ").strip()
    if not user_name:
        user_name = "User"
    print(Fore.GREEN + f"Welcome, {user_name}! Let's give your text some AI magic ✨.")

    # Prompt the user for text input
    print(Fore.YELLOW + Style.BRIGHT + "\nPlease enter the text you want to summarize:") # prompts the user to enter the text they want to summarize, with a bright yellow color for emphasis.
    user_text = input("> ").strip() # reads the user's input text and removes any leading or trailing whitespace. This is the text that will be sent to the Hugging Face API for summarization.

    if not user_text:
        print(Fore.RED + "❌ No text provided. Exiting.")
    else:
        # Ask the user for the model they want to use
        print(Fore.YELLOW + "\nEnter the model name you want to use (e.g., facebook/bart-large-cnn):")
        model_choice = input("Model name (leave blank for default): ").strip()
        if not model_choice:
            model_choice = DEFAULT_MODEL

        # Ask for the summarization style
        print(Fore.YELLOW + "\nChoose your summarization style:")
        print("1. Standard Summary (Quick & concise)")
        print("2. Enhanced Summary (More detailed and refined)")
        style_choice = input("Enter 1 or 2: ").strip() # users choice for summarisation style, which will determine the min and max length of the summary generated by the Hugging Face API. The user can choose between a standard summary (option 1) or an enhanced summary (option 2), which will affect the level of detail in the generated summary.

        if style_choice == "2":
            min_length = 80
            max_length = 200
            print(Fore.BLUE + "Enhancing summarization process... ????")
        else:
            min_length = 50
            max_length = 150
            print(Fore.BLUE + "Using standard summarization settings... ????")

        # Generate the summary using the chosen model and settings
        summary = summarize_text(user_text, min_length, max_length, model_name=model_choice)
        if summary:
            print(Fore.GREEN + Style.BRIGHT + f"\n???? AI Summarizer Output for {user_name}:")
            print(Fore.GREEN + summary)
        else:
            print(Fore.RED + "❌ Failed to generate summary.")